orbs:
  react: thefrontside/react@0.2.0
version: 2

  
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - build:
    docker:
      - image: katalonstudio/katalon:6.3.3
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="test/Test Suites/SignUp"
          requires:
            - react/install

