version: 2
jobs:
  build:
    docker:
    - image: circleci/node:lts
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: npm install
    - save_cache:
        paths:
        - ./node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        command: CI=false npm run build
    - run:
        name: Add Project Firebase
        command: ./node_modules/.bin/firebase use tutor-reactjs
    - run:
        name: Firebase Deploy
        command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
  test:
    docker:
    - image: katalonstudio/katalon:6.3.3
    steps:
    - checkout
    - run: cd test && pwd
    - run:
        name: Execute Katalon Studio
        command: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="test/Test Suites/SignUp"
workflows:
  build_and_test:
    jobs:
    - build
    - test:
        requires:
        - build
  version: 2 
# orbs:
#   react: thefrontside/react@0.2.0
# version: 2.1
# jobs:
#   react/install:
#     docker:
#     - image: circleci/node:10
#     steps:
#     - checkout
#     - restore_cache:
#         key: v1-node-modules-{{ checksum "yarn.lock" }}
#     - run:
#         command: yarn install
#     - persist_to_workspace:
#         paths:
#         - project
#         root: ~/
#     - save_cache:
#         key: v1-node-modules-{{ checksum "yarn.lock" }}
#         paths:
#         - ~/project/node_modules
#   react/build:
#     docker:
#     - image: circleci/node:10
#     steps:
#     - attach_workspace:
#         at: ~/
#     - run:
#         command: mkdir -p artifacts
#         name: Ensure artifacts directory is present
#     - run:
#         command: NODE_ENV=production yarn build
#     - run:
#         command: cp -r build artifacts
#     - store_artifacts:
#         path: ./artifacts
#   test:
#     docker:
#     - image: katalonstudio/katalon:6.3.3
#     steps:
#     - checkout
#     - run:
#         name: Execute Katalon Studio
#         command: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="test/Test Suites/SignUp"
# workflows:
#   push:
#     jobs:
#     - react/install
#     - react/build:
#         requires:
#         - react/install
#     - test:
#         requires:
#         - react/build
