version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Excute Katalon Studio
          command: katalon-excute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath='Test Suites/TS_RegressionTest'
      -store-test_results:
        path: ./report
      -store-artisfacts:
        path: ./report