<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LogoSign inSign upTechnologyDesignCultu_8a3c73</name>
   <tag></tag>
   <elementGuidId>dbbdff95-87ff-45a1-98fe-9a214f06c6f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#root > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logo...Sign inSign upTechnologyDesignCultureBusinessPoliticsOpinionScienceHealthStyleTravel FilterRating1 Star2 Stars3 Stars4 Stars5 StarsHourly Price($)0100Address --- Province *​ --- District *​---Major Skills --- ​OKSee All&lt;1>FooterSomething here to give the footer a purpose!Copyright ©My Website 2020.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
   </webElementXpaths>
</WebElementEntity>
